### ISSUE TITLE
nvim incompatible

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/aw-watcher-vim#1]
Looked into it and tried to fix, didn't have time to finish for now though so leaving this issue here for now

**Comment by johan-bjareholt** [comment]
Just tried with normal vim, it creates a bucket and inserts an event but the event seems to always be 0

**Comment by ahnlabb** [comment]
Thank you I just use classic so I didn't check that, job control is quite different but I'm almost finished with a patch for neovim.

**Comment by ahnlabb** [comment]
Strange that you're just getting 0. Has something big changed in the AW api that might cause this on the newer versions? I will have to recompile and see if I can reproduce it here but I will first upload the neovim patch.
EDIT: see if beb7e77d0159fc90170074a2f8a7af82c5579c17 fixes the neovim issue
EDIT2: v0.8.0b3 seems fine... could you elaborate on the 0 part? Is that 0 seconds, an event with the json data fname: 0 or 0 as in a completely empty event?

**Comment by johan-bjareholt** [comment]
> Strange that you're just getting 0. Has something big changed in the AW api that might cause this on the newer versions? I will have to recompile and see if I can reproduce it here but I will first upload the neovim patch.

Sorry for being unclear, meant a duration of 0, timestamp and data seemed to be fine.
Nothing has changed with the heartbeat API really, should be fine.

> EDIT2: v0.8.0b3 seems fine... could you elaborate on the 0 part? Is that 0 seconds, an event with the json data fname: 0 or 0 as in a completely empty event?

Your server might be 0.8.0b3 but your aw-client cannot be the version of a packaged , do "pip3 install git+git@github.com:ActivityWatch/aw-client.git" to update your aw-client (and do the same with aw-core).

After replacing deprecated setup_bucket with create_bucket like this:
```
-    aw.setup_bucket(bucketname, 'currently-editing')
+    aw.create_bucket(bucketname, 'currently-editing', queued=True)
```
it created a bucket in neovim with your new commit, but I get no events at all.

**Comment by johan-bjareholt** [comment]
Any tips for debugging vim plugins in general?

**Comment by ahnlabb** [comment]
Neovim sent events for me but I will try with an updated client as well and then investigate further. As for the 0 duration, have you tried being actually active in vim for 20s or so? I just want to log actual activity and after a discussion with @ErikBjare I set the pulse time to something quite low meaning that events more than a few seconds apart won't register as continuous activity. If you think it should be done differently have a look at the python code.

**Comment by johan-bjareholt** [comment]
Seems to work well in normal vim now with the last commit, not sure what was wrong before.

**Comment by johan-bjareholt** [comment]
```
function! s:Poke()
        let s:number_of_moves += 1
        if (localtime() - s:vimwatcher_last) >= s:vimwatcher_conf['min_delay'] && s:vimwatcher_open
                call s:SendData()
                let s:vimwatcher_last = localtime()
                let s:number_of_moves = 0
        endif
endfunc
```
Also, the time check here shouldn't be needed anymore in the latest aw-client version which has pre-merging built-in. The min_delay is the "commit_interval" value in aw-client.ini

**Comment by johan-bjareholt** [comment]
Made a WIP branch

https://github.com/ActivityWatch/aw-watcher-vim/tree/dev/testing

**Comment by johan-bjareholt** [comment]
Made a WIP PR https://github.com/ActivityWatch/aw-watcher-vim/pull/2

The issue was simple, we were missing a newline after each jobsend. Closing this issue.
