### ISSUE TITLE
Not working in vim 8

### ISSUE THREAD

**Issue by anoopd** [ActivityWatch/aw-watcher-vim#11]
I have Vim 8 with python3 enabled in Ubuntu 18.04, and my plugin manager is Plug . I cloned the directory into `~/.vim/plugged` but it is not working . Can somebody suggest what went wrong ?

**Comment by ErikBjare** [comment]
Read the README, you need to install `aw-core` and `aw-client` with `pip` as these dependencies aren't vendored in yet.

Edit: I also have no experience with plugged, but assuming it works like other plugin managers I suspect the above is your problem.

**Comment by johan-bjareholt** [comment]
But if it was loading properly he'd at least get an error in vim that it failed to start, so it's likely not an issue with aw-watcher-vim but with plugged.

**Comment by anoopd** [comment]
Hi Eric,
                I went through the README and installed both dependencies using pip3 before cloning it to the plugged directory .:)

**Comment by johan-bjareholt** [comment]
I'm sorry, but we can't help you if there's not even a sign of if the plugin is loaded.
You should look into how plugged works.

**Comment by anoopd** [comment]
Ok thank you .
