### ISSUE TITLE
Broken when more than a single vim instance is running

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/aw-watcher-vim#13]
This aw-client PR breaks aw-watcher-vim when having multiple vim instances running https://github.com/ActivityWatch/aw-client/pull/21

It was probably for the better though as it previously was kind of broken when different instances queued up on the same queue and pre-merged heartbeats could mess things up a lot.

**Comment by tyjak** [comment]
Definitly need multi instance, can't use the plugin for now, since I run only vim in terminalS :) Is it a hard work to make it ?

**Comment by johan-bjareholt** [comment]
In vimscript it is very easy to send data to a process opened with stdin which is what we currently do.

One way to support multiple instances would be to have a fifo/pipe file and then let vim to start a a aw-watcher-vim daemon if noone is consuming the fifo/pipe file yet. How easy this is to do in vimscript i don't know and it would break any possible future support for windows. We should probably look at how vim-wakatime does it.
