### ISSUE TITLE
Git branch slow on windows - nvim

### ISSUE THREAD

**Issue by vonPB** [ActivityWatch/aw-watcher-vim#26]
Hi,

I've noticed that the `systemlist()` call in line 110 of  6d2138e2f1095069e2cd4833680d1a5db994d29f drastically slowed down my nvim; pretty much slow motion.

https://user-images.githubusercontent.com/65032978/167946538-4580f472-c394-48db-97df-dcdc4a6f5cd1.mp4

It's more an issue of neovim/windows than with this repo, so feel free to close.
The plugins works just fine on Arch :)

If anyone has a quick fix/idea other than disabling the branch function, I'd appreciate it.

**Comment by johan-bjareholt** [comment]
I think this is important, syncronous commands can be quite slow. aw-watcher-vim already did shell commands prior to this change, but they did so asyncronously, so it did not have an impact on responsiveness. There is nothing more annoying than an unresponsive editor!

I think that the branch detection should be made asyncronous as well. It's also a bit excessive to check git branch on pretty much every time you move the cursor.

**Comment by vonPB** [comment]
Totally agree with you @johan-bjareholt. It would be sufficient to get the branch on buffer change for instance and save it as a global variable instead.

**Comment by johan-bjareholt** [comment]
Maybe just checking every 10-60seconds (possibly configurable) and do it asynchronously would probably be good. Should be a bit more reliable than a buffer change.

**Comment by FilipHarald** [comment]
Ah, my bad. I can look into it this weekend. But I can't promise I'll solve it :)

**Comment by infokiller** [comment]
I can confirm this makes editing in vim totally unusable.
@johan-bjareholt @FilipHarald I think this change should be reverted until there's a more efficient async implementation working.

**Comment by ErikBjare** [comment]
@infokiller I agree, it was my bad to merge too eagerly. Reverted now, see https://github.com/ActivityWatch/aw-watcher-vim/pull/25#issuecomment-1126976506

**Comment by infokiller** [comment]
Thanks @ErikBjare for the quick fix!
