### ISSUE TITLE
vimwatcher.py crashes when launching nvim: heartbeat() got an unexpected keyword argument

### ISSUE THREAD

**Issue by skogsbrus** [ActivityWatch/aw-watcher-vim#6]
### Problem

When launching nvim, `vimwatcher.py` crashes with the following error message:

```
['Traceback (most recent call last):', '  File "/home/johan/.config/nvim/plugged/aw-watcher-vim/plugin/vimwatcher
.py", line 57, in <module>', '    main()', '  File "/home/johan/.config/nvim/plugged/aw-watcher-vim/plugin/vimwat
cher.py", line 53, in main', '    aw.heartbeat(bucketname, event, pulsetime=pulsetime, queued=True, commit_interv
al=3)', 'TypeError: heartbeat() got an unexpected keyword argument ''commit_interval''', '']
Press ENTER or type command to continue 
```
Pressing Enter then gives:
```
['Traceback (most recent call last):', '  File "/home/johan/.config/nvim/plugged/aw-watcher-vim/plugin/vimwatcher
.py", line 57, in <module>', '    main()', '  File "/home/johan/.config/nvim/plugged/aw-watcher-vim/plugin/vimwat
cher.py", line 53, in main', '    aw.heartbeat(bucketname, event, pulsetime=pulsetime, queued=True, commit_interv
['']
Press ENTER or type command to continue
```

Pressing Enter again gives the same error as above, and finally pressing Enter a third time makes the error disappear.

After this, when pressing any key or click, the following error is thrown:

```
Error detected while processing function <SNR>20_Poke[1]..<SNR>20_Send:
line    4:
E900: Invalid channel id
Press ENTER or type command to continue
```

### Environment

I've installed `aw-watcher-vim` with vim-plug by adding `Plug 'ActivityWatch/aw-watcher-vim'` in my vimrc and then running `:PlugInstall`.

I have the latest commit b8ad0e7 installed, with the following aw-packages in pip:

```
[I] ➜  ~ pip3 list | grep aw
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
aw-client (0.3.1, /home/johan/programs/activitywatch/aw-client)
aw-core (0.4.1)
[I] ➜  ~ 
```

aw-programs that are running when the crash occurs:

```
[I] ➜  ~ ps -A | grep aw
 2225 ?        00:00:37 aw-server
18975 ?        00:00:04 aw-qt
19058 ?        00:00:17 aw-watcher-wind
19059 ?        00:00:39 aw-watcher-afk
[I] ➜  ~ 
```

`aw-watcher-vim` successfully creates a bucket that is visible in the web UI, but it contains no data.

**Comment by ErikBjare** [comment]
@johan-andersson01 The issue seemed to have been that the latest version of `aw-client` (which adds the `commit_interval` kwarg) wasn't included in the bundle, it should be fixed in https://github.com/ActivityWatch/activitywatch/commit/7d6898578125700ac29a46f3c3e8e8448ec92b57

**Comment by skogsbrus** [comment]
Nice!! :heart_eyes:

Just tried it and I can confirm that it fixed the problem!
