### ISSUE TITLE
Log messages after startup of VIM

### ISSUE THREAD

**Issue by lumbric** [ActivityWatch/aw-watcher-vim#8]
nvim shows after startup:

```
['INFO:persistqueue.common:Selected pickle protocol: ''4''', '2018-11-17 00:38:09 [INFO ]: Selected pickle protocol: ''4''  (persistqu
eue.common:14)', '']                                                                                                                  
Press ENTER or type command to continue    
```

vim shows the same message, but only the beginning and no "Pess ENTER...". 

This is not a really problem, but I guess this shouldn't be displayed. Is this only my setup?

**Comment by lumbric** [comment]
I guess, VIM plugins shouldn't log with log level INFO in production, but I'm not 100% sure. I added a draft in #9, fixes the issue for me.

**Comment by johan-bjareholt** [comment]
Hm, I don't get that log message but to set it to warning by default seems sane.

Also, nvim support is kind of broken. Added an issue for that https://github.com/ActivityWatch/aw-watcher-vim/issues/10
